@url = http://localhost:8080/api/security

POST {{url}}/create_account HTTP/1.1
Content-Type: application/json

{
    "username": "bob2@gmail.com",
    "password": "password#1",
    "name": "Bob Smith",
    "favorites": [],
    "healthLabels": []
}

###

POST {{url}}/authenticate HTTP/1.1
Content-Type: application/json

{
    "email": "admin@admin.com",
    "password": "Password1!"
}

###
GET http://localhost:8080/api/security/users HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiI2MzQ1YjNjZGMxOGQwZjJjODdjODNiOTQiLCJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsInJvbGVzIjpbeyJyb2xlTmFtZSI6IkFETUlOIiwiYXV0aG9yaXR5Ijp7ImF1dGhvcml0eSI6IkFETUlOIn19XSwiaXNzIjoiZm9vZGllcyIsInN1YiI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTY2NTUxOTU4NywiZXhwIjoxNjY1NTIwNDg3fQ.NUHti1RqaMcvPEHegRXEKjpQabo_9bUaAX76SZrLdbpSvplA-HPatyjWxXM8am5nc1N7zpTsDBPZC-o4sV8KZA
###

GET http://localhost:8080/api/recipe/public/salt HTTP/1.1
Content-Type: application/json

###

GET https://api.edamam.com/api/recipes/v2?type=public&app_id=6cb09ed9&app_key=d6a13e436430e1c7060acb41373f73cf&q=publicfoodfoodquery HTTP/1.1
Content-Type: application/json

###

GET https://api.edamam.com/api/recipes/v2?type=public&q=are%20spaces%20allowed%20in%20here&app_id=4357d5e9&app_key=84496af29c091bb734dab8904e3d9df5 HTTP/1.1
Content-Type: application/json

###

GET https://api.edamam.com/api/recipes/v2?type=public&q=foodies%foodies&app_id=6cb09ed9&app_key=d6a13e436430e1c7060acb41373f73cf HTTP/1.1
Content-Type: application/json

