GET http://localhost:8080/api/solarpanel HTTP/1.1

###

POST http://localhost:8080/api/solarpanel HTTP/1.1
Content-Type: application/json

{
    
    "section": "the hills",
    "row": 2,
    "column": 3,
    "yearInstalled": 1999,
    "material": "POLY_SI",
    "isTracking": false
}

###

POST http://localhost:8080/api/solarpanel HTTP/1.1
Content-Type: application/json

{
    "section": "the FLATS",
    "row": 2,
    "column": 3,
    "yearInstalled": 1999,
    "material": "MONO_SI",
    "isTracking": true
}

### 
PUT http://localhost:8080/api/solarpanel/b986039f-7c8x-479f-9e6a-48781544e598 HTTP/1.1
Content-Type: application/json

{
    "id": "b986039f-7c8x-479f-9e6a-48781544e598",
    "section": "the flats",
    "row": 4,
    "column": 3,
    "yearInstalled": 2000,
    "material": "MONO_SI",
    "isTracking": true
}

###

POST http://localhost:8080/api/solarpanel HTTP/1.1
Content-Type: application/json

{
    "section": "the hills",
    "row": 2,
    "column": 4,
    "yearInstalled": 2010,
    "material": "MONO_SI",
    "isTracking": false
}

###

DELETE http://localhost:8080/api/solarpanel/d18df834-d70c-4498-a762-62ba28c907da HTTP/1.1